### PR TITLE
Update router.js

### PR DESCRIPTION
**Pull request by kevingzhang**
sorry, just now I submit to my own branch. well, this time, on your branch

### CODE REVIEW

**Comment by cooloney** [comment]
Oh, no. this doesn't work on my side. After merging this, I failed to even go to 'test' template. And the 'pageNotFound' didn't show even I try to visit a wrong URL like local:3000/aaaa

**Comment by kevingzhang** [comment]
Have you create a template called 'pageNotFound'?

**Comment by kevingzhang** [comment]
Please give me access to your depot, so I can fix it direct for you. it
works in my machine

**Comment by cooloney** [comment]
I create a template named pageNotFound. It still doesn't work on my side. Is that because iron:router has different version? I'm using 1.0.7 iron:router.

And if I add Router.configure(), 'test' route won't work at all. So weird!

Let me just clone your repo to give a try!

**Comment by cooloney** [comment]
The root cause looks like is this
-  layoutTemplate: 'hello',

I removed the this line. Then everything works now. I guess this layoutTemplate won't change when jumping between different page template.

**Pull request merged**
